// AUTO-GENERATED by `molen types gen` — do not edit.
// Ambient types for the scripts in this directory, from "types/vehicle.types.json".
// `molen scripts check` (or tsc via the jsconfig.json beside this file) checks them.
/** biome-ignore-all format: generated file (stable output beats house wrapping) */
/** biome-ignore-all lint/style/useConsistentArrayType: generated declarations */

/** External airplane/helicopter instance. Y up, Z forward; landing-contact origin. */
type MolenAircraftData = {
  kind: string;
  spec: {
    label: string;
    model: 'airplane' | 'helicopter';
    mass: number;
    span: number;
    length: number;
    height: number;
    centerOfMass: [number, number, number];
    pilotEye: [number, number, number];
    engine?: {
      position: [number, number, number];
      thrustAxis: [number, number, number];
      power: number;
      idleRpm: number;
      spoolRate: number;
      rotorAngularSpeed: number;
      propellerEfficiency?: number;
      maxThrust?: number;
      minPropellerSpeed?: number;
    };
    engines?: {
      position: [number, number, number];
      thrustAxis: [number, number, number];
      power: number;
      idleRpm: number;
      spoolRate: number;
      rotorAngularSpeed: number;
      propellerEfficiency?: number;
      maxThrust?: number;
      minPropellerSpeed?: number;
      id: string;
    }[];
    airplane?: {
      wingPosition: [number, number, number];
      wingArea: number;
      controlAuthoritySpeed: number;
      maxControlAuthority: number;
      pitchAuthority: number;
      pitchResponse: number;
      stallPitchRate: number;
      rollAuthority: number;
      rollResponse: number;
      rudderAuthority: number;
      groundSteerSpeed: number;
      coordinatedTurnMinSpeed: number;
      groundLevelRate: number;
      maxPitch: number;
      maxGroundPitch: number;
      maxRoll: number;
      camberAngle: number;
      flapLift: number;
      postStallFlapEffect: number;
      stallAngle: number;
      stallTransitionAngle?: number;
      yawStability?: number;
      yawInertia?: number;
      thrustYawDamping?: number;
      stallSpeed: number;
      liftSlope: number;
      postStallLift: number;
      postStallDecay: number;
      profileDrag: number;
      inducedDrag: number;
      gearDrag: number;
      flapDrag: number;
      stallDrag: number;
      propellerEfficiency: number;
      maxThrust: number;
      minPropellerSpeed: number;
      lateralDamping: number;
      brakeDeceleration: number;
      rollingDeceleration: number;
      groundTrackRate: number;
    };
    helicopter?: {
      rotorPosition: [number, number, number];
      rotorRadius: number;
      cyclicTilt: number;
      cyclicResponse: number;
      cyclicDamping: number;
      groundLevelRate: number;
      maxTilt: number;
      yawRate: number;
      liftMultiplier: number;
      groundEffect: number;
      translationalLift: number;
      translationalLiftSpeed: number;
      verticalDrag: number;
      horizontalDrag: number;
      quadraticDrag: number;
      groundDeceleration: number;
    };
    hardLandingSpeed: number;
    hardLandingRoll: number;
    hardLandingPitch: number;
    maxSupportStep: number;
    collisionProbes: [number, number, number][];
    visual: {
      rotors: {
        node: string;
        axis: 'x' | 'y' | 'z';
        multiplier: number;
        engine?: string;
      }[];
      gearNodes: string[];
      flaps: {
        node: string;
        axis: 'x' | 'y' | 'z';
        multiplier: number;
      }[];
      ailerons: {
        node: string;
        axis: 'x' | 'y' | 'z';
        multiplier: number;
      }[];
      controlStick?: {
        node: string;
        pitchAxis: 'x' | 'y' | 'z';
        rollAxis: 'x' | 'y' | 'z';
      };
      collective?: {
        node: string;
        axis: 'x' | 'y' | 'z';
        multiplier: number;
      };
      airspeedGaugeMax?: number;
      interior?: {
        nodes: string[];
        sources?: Record<string, {
            component: string;
            path: string | number[];
          }>;
        bindings: {
          node: string;
          source: string;
          property: 'rotation' | 'position';
          axis: 'x' | 'y' | 'z';
          scale: number;
          offset?: number;
          min?: number;
          max?: number;
        }[];
      };
    };
  };
};
/** Pilot flight controls. Power is retained when input keys are released. */
type MolenAircraftInputData = {
  power: number;
  pitch: number;
  roll: number;
  yaw: number;
  brake: boolean;
  engine: boolean;
  engines?: Record<string, {
      power?: number;
      enabled?: boolean;
    }>;
  gear: boolean;
  flaps: boolean;
};
/** Deterministic flight state, including rotor phase and engine spool, preserved by keyframes. */
type MolenAircraftStateData = {
  velocity: [number, number, number];
  yaw: number;
  pitch: number;
  roll: number;
  pitchRate: number;
  rollRate: number;
  thrustYawRate?: number;
  engines?: Record<string, {
      rpm: number;
      rotorAngle: number;
      failed: boolean;
      thrust: number;
    }>;
  rpm: number;
  rotorAngle: number;
  airspeed: number;
  altitudeAGL: number;
  verticalSpeed: number;
  angleOfAttack: number;
  stalled: boolean;
  grounded: boolean;
  crashed: boolean;
  waitingForTerrain: boolean;
};
/** Kinematic character controller state (speed/jump/gravity + kernel-owned vy/grounded). */
type MolenCharacterData = {
  speed: number;
  jumpSpeed: number;
  gravity: number;
  vy: number;
  grounded: boolean;
};
/** 2.5D kinematic collider (circle or XZ AABB) with layer/mask bitmasks. */
type MolenColliderData = {
  shape: 'circle';
  radius?: number;
  layer: number;
  mask: number;
  isStatic?: boolean;
} | {
  shape: 'aabb';
  halfExtents?: [number, number];
  layer: number;
  mask: number;
  isStatic?: boolean;
};
/** 3D collider (ball/cuboid/capsule/hull/trimesh/asset/heightfield) with layer/mask, sensor, and material params. Static without a rigidbody. */
type MolenCollider3dData = {
  shape: {
    type: 'ball';
    radius: number;
  } | {
    type: 'cuboid';
    hx: number;
    hy: number;
    hz: number;
  } | {
    type: 'capsule';
    halfHeight: number;
    radius: number;
  } | {
    type: 'convexHull';
    points: number[];
  } | {
    type: 'trimesh';
    vertices: number[];
    indices: number[];
  } | {
    type: 'asset';
    assetId: string;
    collision?: 'hull' | 'trimesh';
    index?: number;
  } | {
    type: 'heightfield';
    ref: string;
  };
  offset?: [number, number, number];
  rotOffset?: [number, number, number, number];
  layer?: number;
  mask?: number;
  sensor?: boolean;
  events?: boolean;
  restitution?: number;
  friction?: number;
  density?: number;
};
/** Singleton scene environment: optional Earth/custom sky, ambient/sun lighting, background, fog, tone mapping, shadow quality tier. */
type MolenEnvironmentData = {
  sky?: {
    palette?: {
      dayZenith?: string;
      dayHorizon?: string;
      twilight?: string;
      nightZenith?: string;
      nightHorizon?: string;
      ground?: string;
      sun?: string;
      moon?: string;
    };
    lighting?: {
      sunIntensity?: number;
      moonIntensity?: number;
      dayAmbient?: number;
      nightAmbient?: number;
      castShadow?: boolean;
    };
    stars?: {
      enabled?: boolean;
      magnitudeLimit?: number;
      intensity?: number;
      size?: number;
    };
    sun?: {
      visible?: boolean;
      size?: number;
    };
    moon?: {
      visible?: boolean;
      size?: number;
      earthshine?: number;
    };
    mode: 'earth';
    observer: {
      latitude: number;
      longitude: number;
      elevation?: number;
      northOffsetDeg?: number;
    };
    time: {
      epochMs: number;
      scale?: number;
    };
  } | {
    palette?: {
      dayZenith?: string;
      dayHorizon?: string;
      twilight?: string;
      nightZenith?: string;
      nightHorizon?: string;
      ground?: string;
      sun?: string;
      moon?: string;
    };
    lighting?: {
      sunIntensity?: number;
      moonIntensity?: number;
      dayAmbient?: number;
      nightAmbient?: number;
      castShadow?: boolean;
    };
    stars?: {
      enabled?: boolean;
      magnitudeLimit?: number;
      intensity?: number;
      size?: number;
    };
    sun?: {
      visible?: boolean;
      size?: number;
    };
    moon?: {
      visible?: boolean;
      size?: number;
      earthshine?: number;
    };
    mode: 'custom';
    sunBody: {
      direction: [number, number, number];
      angularDiameterDeg?: number;
    };
    moonBody?: {
      direction: [number, number, number];
      angularDiameterDeg?: number;
    };
    starRotationDeg?: [number, number, number];
  };
  ambient?: {
    sky?: string;
    ground?: string;
    intensity?: number;
  };
  sun?: {
    direction?: [number, number, number];
    color?: string;
    intensity?: number;
    castShadow?: boolean;
  };
  background?: string;
  fog?: {
    color: string;
    near?: number;
    far?: number;
  };
  toneMapping?: 'none' | 'aces' | 'agx';
  exposure?: number;
  shadows?: 'off' | 'low' | 'medium' | 'high';
};
/** What a figure is: a preset plus descriptor overrides (height, build, proportions, features, palette) and how it faces its motion. Pair with renderable.kind "figure". */
type MolenFigureData = {
  preset: 'human.adult' | 'human.child' | 'human.elder' | 'dog' | 'cat' | 'horse' | 'deer' | 'cow' | 'sheep';
  height?: number;
  build?: number;
  age?: 'child' | 'adult' | 'elder';
  proportions?: {
    legRatio?: number;
    armRatio?: number;
    torsoRatio?: number;
    headScale?: number;
    neckLength?: number;
    neckPitch?: number;
    shoulderWidth?: number;
    hipWidth?: number;
    bodyLength?: number;
    tailLength?: number;
    earSize?: number;
    snoutLength?: number;
  };
  features?: {
    hair?: 'none' | 'cap' | 'bob' | 'long';
    hands?: 'mitten' | 'fingers';
    sleeves?: 'none' | 'short' | 'long';
    legs?: 'shorts' | 'long';
    tail?: 'none' | 'short' | 'long' | 'bushy';
    ears?: 'none' | 'round' | 'pointed' | 'floppy';
    horns?: 'none' | 'short' | 'long' | 'antlers';
    feet?: 'plantigrade' | 'digitigrade' | 'unguligrade';
    mane?: boolean;
  };
  palette?: {
    skin?: string;
    hair?: string;
    eyes?: string;
    top?: string;
    bottom?: string;
    shoes?: string;
    accent?: string;
    markings?: string;
  };
  seed?: string;
  facing?: 'velocity' | 'manual';
  turnRate?: number;
  speedSource?: 'auto' | 'transform' | 'none';
  blendTicks?: number;
};
/** Follow a named socket of the parent figure (with `parent`): the figures systems write localTransform from the evaluated pose each tick. */
type MolenFigureAttachmentData = {
  socket: string;
  offset?: {
    pos?: [number, number, number];
    rot?: [number, number, number, number];
  };
  anchor?: 'origin' | 'pelvis' | 'eye';
};
/** Optional authored control of a figure: a forced mode, a look-at target, joint overrides, and IK goals. */
type MolenFigureIntentData = {
  mode?: 'idle' | 'walk' | 'run' | 'jump' | 'fall' | 'sit' | 'custom';
  lookAt?: {
    pos: [number, number, number];
  } | {
    entity: string;
  };
  overrides?: Record<string, [number, number, number, number]>;
  ik?: Record<string, [number, number, number]>;
  footIk?: boolean;
};
/** Kernel-owned locomotion state of a figure (mode, quantized speed, tick-anchored gait phase). Read it; the figures systems write it. */
type MolenFigureStateData = {
  mode: 'idle' | 'walk' | 'run' | 'jump' | 'fall' | 'sit' | 'custom';
  gait?: 'walk' | 'trot' | 'gallop';
  speed: number;
  travel?: number;
  strideRate: number;
  phaseAt: number;
  phaseAtTick: number;
  modeAtTick: number;
  prevMode?: 'idle' | 'walk' | 'run' | 'jump' | 'fall' | 'sit' | 'custom';
  lookAtTick?: number;
};
/** Continuous force/torque applied every tick while present. */
type MolenForceData = {
  linear?: [number, number, number];
  torque?: [number, number, number];
};
/** Minimal event-driven state machine: transitions fire on world events targeting the entity. */
type MolenFsmData = {
  state: string;
  transitions: {
    from: string;
    event: string;
    to: string;
  }[];
};
/** Common gameplay hit-points component. */
type MolenHealthData = {
  hp: number;
  [key: string]: unknown;
};
/** One-shot impulse/torque; consumed the tick it is applied. */
type MolenImpulseData = {
  v?: [number, number, number];
  torque?: [number, number, number];
};
/** Impulse joint to another body (fixed/revolute/spherical/prismatic + limits/motor). */
type MolenJointData = {
  type: 'fixed' | 'revolute' | 'spherical' | 'prismatic';
  other: string;
  anchor1: [number, number, number];
  anchor2: [number, number, number];
  axis?: [number, number, number];
  limits?: [number, number];
  motor?: {
    targetVel: number;
    maxForce: number;
  };
};
/** Velocity-driven body for the kinematic collision layer. */
type MolenKinematicBodyData = {
  vel: [number, number, number];
  slide: boolean;
};
/** Auto-despawn countdown in ticks. */
type MolenLifetimeData = {
  ticksLeft: number;
};
/** A light source at the entity transform (directional/point/spot). */
type MolenLightData = {
  type: 'directional' | 'point' | 'spot';
  color?: string;
  intensity?: number;
  range?: number;
  angleDeg?: number;
  penumbra?: number;
  castShadow?: boolean;
};
/** Parent-relative transform for entities carrying `parent`. */
type MolenLocalTransformData = {
  pos: [number, number, number];
  rot?: [number, number, number, number];
  scale?: [number, number, number];
  teleport?: boolean;
};
/** Bind same-entity simulation fields to named GLB transform channels. Visual only; no physics writes. */
type MolenModel_signalsData = {
  sources: Record<string, {
      component: string;
      path: string | number[];
    }>;
  bindings: {
    node: string;
    source: string;
    property: 'rotation' | 'position';
    axis: 'x' | 'y' | 'z';
    scale: number;
    offset?: number;
    min?: number;
    max?: number;
  }[];
};
/** Mount points in local meters, ordered safe exit candidates, and interaction reach. Seat position is the rider camera anchor. */
type MolenMountableData = {
  seats: {
    id: string;
    role: 'driver' | 'passenger';
    position: [number, number, number];
  }[];
  exits: [number, number, number][];
  reach: number;
};
/** Rider-to-mount relationship. Occupied seats are exclusive; mounted characters bypass walking physics. */
type MolenMountedData = {
  vehicle: string;
  seat: string;
};
/** Desired planar move direction + jump flag, consumed by the character controller. */
type MolenMoveIntentData = {
  dir: [number, number];
  jump: boolean;
};
/** Attach to a parent entity: transform becomes parent.transform × localTransform each tick. */
type MolenParentData = {
  id: string;
  onParentDestroyed?: 'destroy' | 'detach';
};
/** Deterministic XY platform controller: gravity, swept wall/floor/ceiling collision, jump buffering and coyote time. */
type MolenPlatformBodyData = {
  halfExtents: [number, number];
  vel?: [number, number];
  speed?: number;
  acceleration?: number;
  gravity?: number;
  jumpSpeed?: number;
  grounded?: boolean;
  coyoteTicks?: number;
  bufferTicks?: number;
  grace?: number;
  buffered?: number;
};
/** Input to a platformBody. Scripts translate declared commands to this component. */
type MolenPlatformIntentData = {
  move: number;
  jump?: boolean;
  jumpHeld?: boolean;
};
/** Static XY solid for physics.engine=platformer; Z is ignored. */
type MolenPlatformSolidData = {
  halfExtents: [number, number];
  oneWay?: boolean;
};
/** Client render contract: a primitive, a gltf asset (by project asset id) with optional sub-node, material override, shadows, and clip playback, or a capability-registered kind. */
type MolenRenderableData = {
  kind: 'primitive' | 'gltf' | 'figure';
  ref: string;
  materialRef?: string;
  primitive?: {
    size?: [number, number, number];
  };
  node?: string;
  visible?: boolean;
  shadows?: {
    cast?: boolean;
    receive?: boolean;
  };
  animation?: {
    clip: string;
    speed?: number;
    loop?: 'repeat' | 'once' | 'pingpong';
    paused?: boolean;
    pausedAtTick?: number;
    startTick?: number;
  };
  lod?: 'auto' | 0 | 1 | 2;
};
/** 3D rigid-body dynamics: dynamic, fixed, or kinematicPosition (characters). */
type MolenRigidbodyData = {
  body: 'dynamic' | 'fixed' | 'kinematicPosition';
  gravityScale?: number;
  linearDamping?: number;
  angularDamping?: number;
  ccd?: boolean;
  lockRot?: boolean;
};
/** One-shot velocity set; consumed the tick it is applied. */
type MolenSetVelocityData = {
  linear?: [number, number, number];
  angular?: [number, number, number];
};
/** Named tag for selecting/grouping entities (e.g. tag.name === "enemy"). */
type MolenTagData = {
  name: string;
  [key: string]: unknown;
};
/** Snapshot-safe countdown timers that emit events (one-shot or repeating). Replaces callbacks. */
type MolenTimerData = {
  timers: {
    id: string;
    ticksLeft: number;
    event: string;
    payload?: unknown;
    repeatEvery?: number;
  }[];
};
/** World position + orientation. pos is required; rot defaults to identity. */
type MolenTransformData = {
  pos: [number, number, number];
  rot?: [number, number, number, number];
  scale?: [number, number, number];
  teleport?: boolean;
};
/** Data-driven value animation over ticks: component + select-style path, lerp with easing. */
type MolenTweenData = {
  tweens: {
    id?: string;
    component: string;
    path: string;
    from?: number | number[];
    to: number | number[];
    ticks: number;
    elapsed?: number;
    easing?: 'linear' | 'quadIn' | 'quadOut' | 'quadInOut' | 'cubicIn' | 'cubicOut' | 'cubicInOut';
    loop?: 'none' | 'loop' | 'pingpong';
    emitOnComplete?: string;
  }[];
};
/** External wheeled-vehicle instance: stable id, paint, complete physics tuning, and GLB bindings. */
type MolenVehicleData = {
  kind: string;
  color: string;
  spec: {
    label: string;
    width: number;
    length: number;
    height: number;
    centerOfMass: [number, number, number];
    wheelbase: number;
    wheelTrack: number;
    wheelRadius: number;
    mass: number;
    engineForce: number;
    maxSpeed: number;
    reverseSpeed: number;
    brakeDeceleration: number;
    maxSteer: number;
    grip: number;
    driverEye: [number, number, number];
    steeringRate: number;
    steeringFadeSpeed: number;
    rollingResistance: number;
    aerodynamicResistance: number;
    terrainAlignRate: number;
    supportTolerance: number;
    maxStepHeight: number;
    maxSlope: number;
  };
  visual: {
    wheelNodes: string[];
    frontWheelNodes: string[];
    steeringWheelNode?: string;
    paintMaterial: string;
    interior?: {
      nodes: string[];
      sources?: Record<string, {
          component: string;
          path: string | number[];
        }>;
      bindings: {
        node: string;
        source: string;
        property: 'rotation' | 'position';
        axis: 'x' | 'y' | 'z';
        scale: number;
        offset?: number;
        min?: number;
        max?: number;
      }[];
    };
  };
};
/** Driver intent: signed throttle (negative brakes then reverses), signed steering (positive right), brake/handbrake. */
type MolenVehicleInputData = {
  throttle: number;
  steering: number;
  brake: boolean;
};
/** Snapshot-safe chassis state. Speeds in m/s, angles in radians; owned by installVehicles. */
type MolenVehicleStateData = {
  speed: number;
  steer: number;
  yaw: number;
  pitch: number;
  roll: number;
  vy: number;
  grounded: boolean;
  waitingForTerrain: boolean;
  wheelAngle: number;
};
/** Opt-in per-tick body velocity mirror (presence = subscription; plugin-written). */
type MolenVelocityData = {
  linear: [number, number, number];
  angular: [number, number, number];
};
/** Singleton physical atmosphere and visual weather: temperature, pressure, humidity, wind, independent cloud cover, precipitation and visibility. Readable by scripts and physics; see guide/weather.md. */
type MolenWeatherData = {
  atmosphere?: {
    temperatureK?: number;
    pressurePa?: number;
    relativeHumidity?: number;
    windVelocity?: [number, number, number];
    referenceAltitude?: number;
    gasConstant?: number;
  };
  visibility?: number;
  clouds?: {
    coverage?: number;
    density?: number;
    baseAltitude?: number;
    thickness?: number;
    scale?: number;
  };
  precipitation?: {
    kind?: 'none' | 'rain' | 'snow';
    intensity?: number;
  };
  seed?: number;
};
/** A building generated at runtime from an outline in the entity frame, styled by a molen/archstyle@1 in the loaded pack; rendered by the worldgen client entity layer. */
type MolenWorldgenBuildingData = {
  style: string;
  appearance?: {
    wall?: string;
    trim?: string;
  };
  storefronts?: {
    identity: string;
    at: [number, number];
    signModel: string;
    signSize?: [number, number];
    accent: string;
    width?: number;
  }[];
  outline: [number, number][];
  holes?: [number, number][][];
  height?: number;
  levels?: number;
  labels?: string[];
  seed?: string;
  tier?: number;
  [key: string]: unknown;
};

/** Component name -> data shape, from this project's component vocabulary. */
interface MolenComponentData {
  /** External airplane/helicopter instance. Y up, Z forward; landing-contact origin. */
  'aircraft': MolenAircraftData;
  /** Pilot flight controls. Power is retained when input keys are released. */
  'aircraftInput': MolenAircraftInputData;
  /** Deterministic flight state, including rotor phase and engine spool, preserved by keyframes. */
  'aircraftState': MolenAircraftStateData;
  /** Kinematic character controller state (speed/jump/gravity + kernel-owned vy/grounded). */
  'character': MolenCharacterData;
  /** 2.5D kinematic collider (circle or XZ AABB) with layer/mask bitmasks. */
  'collider': MolenColliderData;
  /** 3D collider (ball/cuboid/capsule/hull/trimesh/asset/heightfield) with layer/mask, sensor, and material params. Static without a rigidbody. */
  'collider3d': MolenCollider3dData;
  /** Singleton scene environment: optional Earth/custom sky, ambient/sun lighting, background, fog, tone mapping, shadow quality tier. */
  'environment': MolenEnvironmentData;
  /** What a figure is: a preset plus descriptor overrides (height, build, proportions, features, palette) and how it faces its motion. Pair with renderable.kind "figure". */
  'figure': MolenFigureData;
  /** Follow a named socket of the parent figure (with `parent`): the figures systems write localTransform from the evaluated pose each tick. */
  'figureAttachment': MolenFigureAttachmentData;
  /** Optional authored control of a figure: a forced mode, a look-at target, joint overrides, and IK goals. */
  'figureIntent': MolenFigureIntentData;
  /** Kernel-owned locomotion state of a figure (mode, quantized speed, tick-anchored gait phase). Read it; the figures systems write it. */
  'figureState': MolenFigureStateData;
  /** Continuous force/torque applied every tick while present. */
  'force': MolenForceData;
  /** Minimal event-driven state machine: transitions fire on world events targeting the entity. */
  'fsm': MolenFsmData;
  /** Common gameplay hit-points component. */
  'health': MolenHealthData;
  /** One-shot impulse/torque; consumed the tick it is applied. */
  'impulse': MolenImpulseData;
  /** Impulse joint to another body (fixed/revolute/spherical/prismatic + limits/motor). */
  'joint': MolenJointData;
  /** Velocity-driven body for the kinematic collision layer. */
  'kinematicBody': MolenKinematicBodyData;
  /** Auto-despawn countdown in ticks. */
  'lifetime': MolenLifetimeData;
  /** A light source at the entity transform (directional/point/spot). */
  'light': MolenLightData;
  /** Parent-relative transform for entities carrying `parent`. */
  'localTransform': MolenLocalTransformData;
  /** Bind same-entity simulation fields to named GLB transform channels. Visual only; no physics writes. */
  'model.signals': MolenModel_signalsData;
  /** Mount points in local meters, ordered safe exit candidates, and interaction reach. Seat position is the rider camera anchor. */
  'mountable': MolenMountableData;
  /** Rider-to-mount relationship. Occupied seats are exclusive; mounted characters bypass walking physics. */
  'mounted': MolenMountedData;
  /** Desired planar move direction + jump flag, consumed by the character controller. */
  'moveIntent': MolenMoveIntentData;
  /** Attach to a parent entity: transform becomes parent.transform × localTransform each tick. */
  'parent': MolenParentData;
  /** Deterministic XY platform controller: gravity, swept wall/floor/ceiling collision, jump buffering and coyote time. */
  'platformBody': MolenPlatformBodyData;
  /** Input to a platformBody. Scripts translate declared commands to this component. */
  'platformIntent': MolenPlatformIntentData;
  /** Static XY solid for physics.engine=platformer; Z is ignored. */
  'platformSolid': MolenPlatformSolidData;
  /** Client render contract: a primitive, a gltf asset (by project asset id) with optional sub-node, material override, shadows, and clip playback, or a capability-registered kind. */
  'renderable': MolenRenderableData;
  /** 3D rigid-body dynamics: dynamic, fixed, or kinematicPosition (characters). */
  'rigidbody': MolenRigidbodyData;
  /** One-shot velocity set; consumed the tick it is applied. */
  'setVelocity': MolenSetVelocityData;
  /** Named tag for selecting/grouping entities (e.g. tag.name === "enemy"). */
  'tag': MolenTagData;
  /** Snapshot-safe countdown timers that emit events (one-shot or repeating). Replaces callbacks. */
  'timer': MolenTimerData;
  /** World position + orientation. pos is required; rot defaults to identity. */
  'transform': MolenTransformData;
  /** Data-driven value animation over ticks: component + select-style path, lerp with easing. */
  'tween': MolenTweenData;
  /** External wheeled-vehicle instance: stable id, paint, complete physics tuning, and GLB bindings. */
  'vehicle': MolenVehicleData;
  /** Driver intent: signed throttle (negative brakes then reverses), signed steering (positive right), brake/handbrake. */
  'vehicleInput': MolenVehicleInputData;
  /** Snapshot-safe chassis state. Speeds in m/s, angles in radians; owned by installVehicles. */
  'vehicleState': MolenVehicleStateData;
  /** Opt-in per-tick body velocity mirror (presence = subscription; plugin-written). */
  'velocity': MolenVelocityData;
  /** Singleton physical atmosphere and visual weather: temperature, pressure, humidity, wind, independent cloud cover, precipitation and visibility. Readable by scripts and physics; see guide/weather.md. */
  'weather': MolenWeatherData;
  /** A building generated at runtime from an outline in the entity frame, styled by a molen/archstyle@1 in the loaded pack; rendered by the worldgen client entity layer. */
  'worldgenBuilding': MolenWorldgenBuildingData;
}

type MolenComponentName = keyof MolenComponentData;
type MolenComponentPatch = { [K in MolenComponentName]?: MolenComponentData[K] };

/** Entity ids declared in the scene. Ids of spawned entities are plain strings. */
type MolenEntityId = string;
/** Prefab names declared in the scene. */
type MolenPrefabName = string;
/** Registry type ids this project declares (`molen.spawnType`). */
type MolenTypeId = 'molen.entities.aircraft.oh6' | 'molen.entities.aircraft.p51d' | 'molen.entities.nature.boulder' | 'molen.entities.tree.conifer.fir' | 'molen.entities.tree.conifer.pine' | 'molen.entities.tree.deciduous.birch' | 'molen.entities.tree.deciduous.oak' | 'molen.entities.vegetation.shrub' | 'molen.entities.vehicle.compact' | 'molen.entities.vehicle.pickup' | 'molen.entities.vehicle.sedan' | 'molen.entities.vehicle.suv' | 'molen.entities.vehicle.van';

/** Command types this scene accepts; this script directory has none. */
type MolenCommands = Record<never, never>;

type MolenCommandName = keyof MolenCommands;

type MolenJsonValue =
  | string
  | number
  | boolean
  | null
  | MolenJsonValue[]
  | { [key: string]: MolenJsonValue };

type MolenVec3 = [number, number, number];
type MolenUnsubscribe = () => void;

interface MolenTickContext {
  readonly tick: number;
  readonly dt: number;
}

interface MolenCommand {
  readonly kind: 	"command";
  readonly type: MolenCommandName;
  readonly seq: number;
  readonly source: string;
  readonly tick: number;
  readonly payload: MolenJsonValue;
}

/** Kinematics collision event (`physics.engine: "kinematics"`). */
interface MolenCollisionEvent {
  readonly a: string;
  readonly b: string;
  readonly normal: MolenVec3;
  readonly point?: MolenVec3;
}

/** Payload of an event emitted by `molen.after` / `molen.every`. */
interface MolenTimerEvent {
  readonly entity: string;
  readonly timerId: string;
  readonly payload?: MolenJsonValue;
}

interface MolenTweenCompleteEvent {
  readonly entity: string;
  readonly id?: string;
}

interface MolenRayHit {
  readonly id: string;
  readonly distance: number;
  readonly point: MolenVec3;
}

interface MolenTweenSpec {
  id?: string;
  component: MolenComponentName;
  /** Value path inside the component, e.g. "pos", "pos[1]", "primitive.size". */
  path: string;
  from?: number | number[];
  to: number | number[];
  ticks: number;
  easing?: 'linear' | 'easeIn' | 'easeOut' | 'easeInOut';
  loop?: 'none' | 'loop' | 'pingpong';
  emitOnComplete?: string;
}

type MolenRow<K extends readonly MolenComponentName[]> = [
  id: string,
  ...{ [I in keyof K]: Readonly<MolenComponentData[K[I] & MolenComponentName]> },
];

/** Iterable query result: `for (const [id, tag, t] of molen.query("tag", "transform"))`. */
interface MolenQuery<K extends readonly MolenComponentName[]> extends Iterable<MolenRow<K>> {
  ids(): readonly string[];
  count(): number;
  first(): MolenRow<K> | undefined;
  /** The same query, excluding entities carrying ANY of the named components. */
  without(...components: MolenComponentName[]): MolenQuery<K>;
}

/** Deterministic math (dmath). `Math.random`, `Date` and `Intl` are absent. */
interface MolenMath {
  readonly PI: number;
  readonly TAU: number;
  sqrt(x: number): number;
  abs(x: number): number;
  min(a: number, b: number): number;
  max(a: number, b: number): number;
  floor(x: number): number;
  ceil(x: number): number;
  round(x: number): number;
  sign(x: number): number;
  hypot(x: number, y: number, z?: number): number;
  clamp(x: number, lo: number, hi: number): number;
  lerp(a: number, b: number, t: number): number;
  frac(x: number): number;
  smoothstep(x: number): number;
  wrapAngle(a: number): number;
  sin(x: number): number;
  cos(x: number): number;
  tan(x: number): number;
  asin(x: number): number;
  acos(x: number): number;
  atan(x: number): number;
  atan2(y: number, x: number): number;
  pow(x: number, y: number): number;
  exp(x: number): number;
  log(x: number): number;
  log2(...args: number[]): number;
  log10(...args: number[]): number;
  cbrt(...args: number[]): number;
}

/** The verb set injected into every scene-data script as `molen`. */
interface MolenApi {
  /** Spawn from a component map. */
  spawn(components: MolenComponentPatch, id?: string): string;
  /** Spawn a scene prefab, with optional components layered on top. */
  spawn(prefab: MolenPrefabName, components?: MolenComponentPatch, id?: string): string;
  /** Instantiate a project registry type with optional overrides. */
  spawnType(type: MolenTypeId, components?: MolenComponentPatch, id?: string): string;
  /**
   * Script-owned durable JSON state (checkpointed, survives reload). Untyped by design —
   * annotate a read with JSDoc when you want it checked.
   */
  // biome-ignore lint/suspicious/noExplicitAny: script state is free-form JSON
  readonly state: any;
  setState(data: Record<string, MolenJsonValue>): void;
  patchState(partial: Record<string, MolenJsonValue>): void;
  destroy(id: MolenEntityId): void;
  exists(id: MolenEntityId): boolean;
  /** The stored component object, frozen. Never mutate it — write with set/patch. */
  get<K extends MolenComponentName>(
    id: MolenEntityId,
    component: K,
  ): Readonly<MolenComponentData[K]> | undefined;
  set<K extends MolenComponentName>(
    id: MolenEntityId,
    component: K,
    data: MolenComponentData[K],
  ): void;
  patch<K extends MolenComponentName>(
    id: MolenEntityId,
    component: K,
    partial: Partial<MolenComponentData[K]>,
  ): void;
  remove(id: MolenEntityId, component: MolenComponentName): void;
  has(id: MolenEntityId, component: MolenComponentName): boolean;
  /** Entities carrying every named component, in creation order. */
  query<K extends MolenComponentName[]>(...components: K): MolenQuery<K>;
  /** Run every tick, in the update phase. */
  on(event: 'tick', handler: (payload: null, ctx: MolenTickContext) => void): MolenUnsubscribe;
  on(
    event: 'collision',
    handler: (payload: MolenCollisionEvent, ctx: MolenTickContext) => void,
  ): MolenUnsubscribe;
  on(
    event: 'tween-complete',
    handler: (payload: MolenTweenCompleteEvent, ctx: MolenTickContext) => void,
  ): MolenUnsubscribe;
  /** Timer and custom events: the payload is whatever the emitter sent. */
  // biome-ignore lint/suspicious/noExplicitAny: event payloads are emitter-defined JSON
  on(event: string, handler: (payload: any, ctx: MolenTickContext) => void): MolenUnsubscribe;
  /** Handle player/agent input. Undeclared types are rejected before any handler runs. */
  onCommand<T extends MolenCommandName>(
    type: T,
    handler: (payload: MolenCommands[T], ctx: MolenTickContext, command: MolenCommand) => void,
  ): MolenUnsubscribe;
  emit(type: string, payload?: MolenJsonValue): void;
  raycast(origin: MolenVec3, dir: MolenVec3, maxDist: number, mask?: number): MolenRayHit | null;
  overlapCircle(center: MolenVec3, radius: number, mask?: number): string[];
  /** Emit `event` after `ticks` ticks (snapshot-safe world timer). Returns the timer id. */
  after(ticks: number, event: string, payload?: MolenJsonValue): string;
  /** Emit `event` every `ticks` ticks. Returns the timer id. */
  every(ticks: number, event: string, payload?: MolenJsonValue): string;
  cancelTimer(timerId: string, entity?: MolenEntityId): void;
  tween(entity: MolenEntityId, spec: MolenTweenSpec): void;
  cancelTween(entity: MolenEntityId, tweenId?: string): void;
  parent(id: MolenEntityId, parentId: MolenEntityId): void;
  unparent(id: MolenEntityId): void;
  /** The only source of randomness — deterministic, seeded by the world. */
  rng(): number;
  readonly tick: number;
  readonly dt: number;
  readonly math: MolenMath;
}

/**
 * The script's own `config` block from scene.json, frozen. Keys from every script in this
 * directory are merged here (one ambient global covers the directory), each tagged with the
 * script that declares it.
 */
interface MolenScriptConfig {
  /** script 'molen.entities.vehicle.van:interactions' */
  readonly type: string;
}

/** The verb set (see guide/scripting.md). */
declare const molen: MolenApi;
/** This script's `config` block from the scene manifest, frozen. */
declare const config: MolenScriptConfig;
