/** Procedural body recipes and conservative habitat priors; source-derived ranges are separate. */
import { readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const animals = [];
const rules = [];
const land = ['forest', 'wood', 'scrub', 'grass', 'meadow'];
const grass = ['grass', 'meadow', 'scrub'];
function animal(
  name,
  taxon,
  family,
  dimensions,
  color,
  accent,
  details,
  biomes,
  realms,
  habitats,
  options = {},
) {
  const id = `molen.wildlife.animal.${name}`;
  animals.push({
    id,
    version: 1,
    title: name.replaceAll('_', ' '),
    ...(taxon ? { taxon: taxon.replaceAll('_', ' '), range: taxon } : {}),
    ...(options.winterColor ? { winterColor: options.winterColor } : {}),
    ...(['reptile', 'insect'].includes(family) ? { inactiveInWinter: true } : {}),
    body: {
      family,
      height: dimensions[0],
      length: dimensions[1],
      width: dimensions[2],
      color,
      accent,
      details,
    },
    motion: options.motion ?? 'walk',
    speed: options.speed ?? 0.8,
    roam: options.roam ?? 24,
    clearance: options.clearance ?? 0,
    rest: options.rest ?? 0.6,
    margin: options.margin ?? Math.max(0.2, dimensions[2] * 0.7),
  });
  rules.push({
    animal: id,
    density: options.density ?? 5,
    habitats,
    match: { ...(biomes ? { biomes } : {}), ...(realms ? { realms } : {}) },
    ...(options.nearWater !== undefined ? { nearWater: options.nearWater } : {}),
    ...(options.protectedOnly ? { protectedOnly: true } : {}),
  });
}
animal(
  'roe_deer',
  'Capreolus_capreolus',
  'ungulate',
  [0.72, 1.1, 0.33],
  '#947258',
  '#d9cdb2',
  ['antlers'],
  [4, 5, 8, 12],
  ['Palearctic'],
  land,
  { density: 9 },
);
animal(
  'white_tailed_deer',
  'Odocoileus_virginianus',
  'ungulate',
  [0.95, 1.65, 0.4],
  '#8e7358',
  '#eee0c5',
  ['antlers'],
  [1, 2, 4, 5, 7, 8],
  ['Nearctic', 'Neotropic'],
  land,
  { density: 8 },
);
animal(
  'red_deer',
  'Cervus_elaphus',
  'ungulate',
  [1.2, 1.9, 0.47],
  '#78604a',
  '#c3a486',
  ['antlers'],
  [4, 5, 8, 12],
  ['Palearctic'],
  land,
);
animal(
  'wapiti',
  'Cervus_canadensis',
  'ungulate',
  [1.45, 2.2, 0.56],
  '#a18b68',
  '#544737',
  ['antlers'],
  [4, 5, 6, 8, 10],
  ['Nearctic', 'Palearctic'],
  land,
  { density: 3 },
);
animal(
  'moose',
  'Alces_alces',
  'ungulate',
  [1.9, 2.7, 0.7],
  '#5e5548',
  '#a0957e',
  ['antlers', 'long-neck'],
  [6],
  ['Nearctic', 'Palearctic'],
  ['forest', 'wood', 'wetland'],
  { density: 2 },
);
animal(
  'reindeer',
  'Rangifer_tarandus',
  'ungulate',
  [1.05, 1.8, 0.48],
  '#8e8b7a',
  '#d8d5c5',
  ['antlers'],
  [6, 11],
  ['Nearctic', 'Palearctic'],
  ['forest', 'wood', 'grass', 'scrub', 'tundra'],
  { density: 4 },
);
animal(
  'impala',
  'Aepyceros_melampus',
  'ungulate',
  [0.9, 1.4, 0.32],
  '#b48b5b',
  '#eadac0',
  ['horns'],
  [7, 9],
  ['Afrotropic'],
  grass,
  { protectedOnly: true, density: 14 },
);
animal(
  'springbok',
  'Antidorcas_marsupialis',
  'ungulate',
  [0.78, 1.2, 0.3],
  '#bba074',
  '#eee4d0',
  ['horns'],
  [7, 8, 13],
  ['Afrotropic'],
  grass,
  { protectedOnly: true, density: 12 },
);
animal(
  'gemsbok',
  'Oryx_gazella',
  'ungulate',
  [1.2, 1.9, 0.49],
  '#a4977e',
  '#353831',
  ['horns'],
  [7, 13],
  ['Afrotropic'],
  grass,
  { protectedOnly: true, density: 5 },
);
animal(
  'plains_zebra',
  'Equus_quagga',
  'ungulate',
  [1.35, 2.2, 0.57],
  '#e0dbc9',
  '#3b3b36',
  ['stripes'],
  [7, 9],
  ['Afrotropic'],
  grass,
  { protectedOnly: true, density: 10 },
);
animal(
  'savanna_elephant',
  'Loxodonta_africana',
  'elephant',
  [3.2, 5.2, 1.8],
  '#817d72',
  '#c7c0a9',
  [],
  [2, 7, 9, 13],
  ['Afrotropic'],
  land,
  { protectedOnly: true, density: 1, roam: 45, speed: 0.7 },
);
animal(
  'asian_elephant',
  'Elephas_maximus',
  'elephant',
  [2.7, 4.8, 1.6],
  '#858177',
  '#bbb6a4',
  [],
  [1, 2, 7],
  ['Indomalayan'],
  land,
  { protectedOnly: true, density: 1, roam: 35 },
);
animal(
  'red_kangaroo',
  'Osphranter_rufus',
  'hopper',
  [1.5, 1.25, 0.45],
  '#ad8065',
  '#d8c6aa',
  ['long-tail'],
  [7, 8, 13],
  ['Australasia'],
  grass,
  { motion: 'hop', speed: 1.6, density: 8, roam: 35 },
);
animal(
  'eastern_grey_kangaroo',
  'Macropus_giganteus',
  'hopper',
  [1.45, 1.3, 0.46],
  '#8e8a7c',
  '#c4bca8',
  ['long-tail'],
  [1, 4, 7, 8, 12],
  ['Australasia'],
  grass,
  { motion: 'hop', speed: 1.6, density: 8 },
);
animal(
  'capybara',
  'Hydrochoerus_hydrochaeris',
  'rodent',
  [0.55, 1.15, 0.45],
  '#8c795e',
  '#b8a68a',
  [],
  [1, 2, 7, 9, 14],
  ['Neotropic'],
  ['wetland', 'grass', 'meadow'],
  { nearWater: 30, density: 10, speed: 0.45 },
);
animal(
  'red_fox',
  'Vulpes_vulpes',
  'canid',
  [0.4, 0.75, 0.22],
  '#ac714a',
  '#e0d7bd',
  ['bushy-tail'],
  [4, 5, 6, 8, 10, 11, 12, 13],
  ['Nearctic', 'Palearctic'],
  land,
  { density: 2, speed: 0.9 },
);
animal(
  'arctic_fox',
  'Vulpes_lagopus',
  'canid',
  [0.3, 0.6, 0.22],
  '#918d7f',
  '#9d9c8f',
  ['bushy-tail'],
  [11],
  ['Nearctic', 'Palearctic'],
  ['tundra', 'grass', 'scrub'],
  { density: 2, winterColor: '#deddd1' },
);
animal(
  'european_hare',
  'Lepus_europaeus',
  'lagomorph',
  [0.38, 0.55, 0.2],
  '#978a6d',
  '#d5c9ab',
  [],
  [4, 5, 8, 12],
  ['Palearctic'],
  grass,
  { motion: 'hop', speed: 1.1, density: 10 },
);
animal(
  'black_tailed_jackrabbit',
  'Lepus_californicus',
  'lagomorph',
  [0.4, 0.6, 0.22],
  '#9b9175',
  '#d7ccb1',
  [],
  [8, 12, 13],
  ['Nearctic'],
  grass,
  { motion: 'hop', speed: 1.3, density: 8 },
);
animal(
  'red_squirrel',
  'Sciurus_vulgaris',
  'rodent',
  [0.2, 0.24, 0.11],
  '#a07854',
  '#d9cbb0',
  ['bushy-tail'],
  [4, 5, 6],
  ['Palearctic'],
  ['forest', 'wood', 'park'],
  { density: 15, speed: 0.55, roam: 12 },
);
animal(
  'eastern_grey_squirrel',
  'Sciurus_carolinensis',
  'rodent',
  [0.22, 0.28, 0.12],
  '#97978b',
  '#d5d3c2',
  ['bushy-tail'],
  [4, 5],
  ['Nearctic'],
  ['forest', 'wood', 'park'],
  { density: 15, speed: 0.55, roam: 12 },
);
// These silhouettes represent functional groups. They deliberately have no scientific name or
// asserted occurrence range. Realm/biome and actual mapped habitat still constrain placement.
animal(
  'woodland_songbird',
  null,
  'bird',
  [0.16, 0.2, 0.085],
  '#7a7564',
  '#c3b997',
  [],
  [1, 2, 3, 4, 5, 6, 12],
  null,
  ['forest', 'wood', 'park', 'scrub'],
  { motion: 'fly', speed: 3, clearance: 8, roam: 45, rest: 0, density: 45 },
);
animal(
  'open_country_raptor',
  null,
  'bird',
  [0.45, 0.6, 0.22],
  '#5a5344',
  '#ad9f7e',
  ['raptor'],
  [2, 4, 5, 6, 7, 8, 10, 11, 12, 13],
  null,
  ['grass', 'meadow', 'scrub', 'forest', 'wood', 'tundra'],
  { motion: 'fly', speed: 5, clearance: 30, roam: 90, rest: 0, density: 1 },
);
animal(
  'tropical_parrot_group',
  null,
  'bird',
  [0.34, 0.42, 0.16],
  '#668758',
  '#b7a366',
  ['parrot', 'long-tail'],
  [1, 2, 7],
  ['Neotropic', 'Afrotropic', 'Indomalayan', 'Australasia'],
  ['forest', 'wood'],
  { motion: 'fly', speed: 3.5, clearance: 14, roam: 55, rest: 0, density: 12 },
);
animal(
  'waterfowl_group',
  null,
  'bird',
  [0.32, 0.55, 0.25],
  '#7b7862',
  '#c9bea0',
  ['waterfowl'],
  [1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14],
  null,
  ['water', 'freshwater', 'wetland'],
  { motion: 'swim', clearance: 0, speed: 0.35, roam: 18, density: 18, rest: 0 },
);
animal(
  'wading_bird_group',
  null,
  'bird',
  [0.85, 0.5, 0.2],
  '#9ea59e',
  '#d3d2b9',
  ['wader'],
  [1, 2, 4, 7, 8, 9, 12, 14],
  null,
  ['wetland', 'grass', 'meadow'],
  { nearWater: 12, speed: 0.25, density: 8, roam: 12 },
);
animal(
  'coastal_gull_group',
  null,
  'bird',
  [0.3, 0.5, 0.2],
  '#c3c8c2',
  '#565f61',
  [],
  null,
  null,
  ['beach', 'coast'],
  { motion: 'fly', speed: 4, clearance: 10, roam: 65, rest: 0, density: 22 },
);
animal(
  'warm_ground_lizard',
  null,
  'reptile',
  [0.07, 0.22, 0.065],
  '#9a9671',
  '#c4b58f',
  ['long-tail'],
  [1, 2, 7, 8, 12, 13],
  null,
  ['scrub', 'grass', 'rock', 'sand'],
  { motion: 'crawl', speed: 0.15, roam: 5, density: 12 },
);
animal(
  'freshwater_fish_group',
  null,
  'fish',
  [0.12, 0.35, 0.075],
  '#88988a',
  '#b8c4ad',
  [],
  [1, 2, 4, 5, 6, 7, 8, 9, 12, 14],
  null,
  ['freshwater'],
  { motion: 'swim', clearance: 0.4, speed: 0.45, roam: 12, rest: 0, density: 25 },
);
animal(
  'flower_visiting_insect',
  null,
  'insect',
  [0.025, 0.045, 0.02],
  '#c7a36a',
  '#6d684b',
  [],
  [1, 2, 4, 7, 8, 9, 12, 14],
  null,
  ['meadow', 'grass', 'park'],
  { motion: 'fly', clearance: 0.6, speed: 0.2, roam: 3, rest: 0, density: 30, margin: 0.05 },
);
const doc = {
  format: 'molen/regional-catalog@1',
  id: 'molen.wildlife.regional',
  version: 1,
  title: 'Regional wildlife populations',
  requires: [{ id: 'molen.ecology.regional', version: 1 }],
  overrides: [],
  profiles: [
    {
      id: 'molen.wildlife.habitat.global',
      title: 'Habitat and range constrained fauna',
      priority: 0,
      match: {},
      wildlife: 'molen.wildlife.population.global',
    },
  ],
  scatters: [],
  animals,
  populations: [
    { id: 'molen.wildlife.population.global', title: 'Conservative global wildlife', rules },
  ],
};
const text = `${JSON.stringify(doc, null, 2)}\n`;
const path = new URL('regional.catalog.json', root);
if (process.argv.includes('--check')) {
  if ((await readFile(path, 'utf8')) !== text)
    throw new Error('Wildlife catalog is stale; run build-catalog.mjs');
} else await writeFile(path, text);
console.log(
  `${animals.length} wildlife recipes, ${animals.filter((animal) => animal.taxon).length} named mammal taxa`,
);
