// Generated by scripts/generate-landmark-index.mjs. Edit source/landmarks/*/landmark.json.
import landmark0 from '../../packs/default/landmarks/bench.landmark.json';
import landmark1 from '../../packs/default/landmarks/bike_rack.landmark.json';
import landmark2 from '../../packs/default/landmarks/bread_cafe.landmark.json';
import landmark3 from '../../packs/default/landmarks/burger_diner.landmark.json';
import landmark4 from '../../packs/default/landmarks/burger_place.landmark.json';
import landmark5 from '../../packs/default/landmarks/burger_restaurant.landmark.json';
import landmark6 from '../../packs/default/landmarks/burrito_grill.landmark.json';
import landmark7 from '../../packs/default/landmarks/cafe.landmark.json';
import landmark8 from '../../packs/default/landmarks/charger.fast.landmark.json';
import landmark9 from '../../packs/default/landmarks/charger.landmark.json';
import landmark10 from '../../packs/default/landmarks/chicken_kitchen.landmark.json';
import landmark11 from '../../packs/default/landmarks/chicken_restaurant.landmark.json';
import landmark12 from '../../packs/default/landmarks/clothing_outlet.landmark.json';
import landmark13 from '../../packs/default/landmarks/coat_outlet.landmark.json';
import landmark14 from '../../packs/default/landmarks/coffee_shop.landmark.json';
import landmark15 from '../../packs/default/landmarks/community_market.landmark.json';
import landmark16 from '../../packs/default/landmarks/corner_pharmacy.landmark.json';
import landmark17 from '../../packs/default/landmarks/department_store.landmark.json';
import landmark18 from '../../packs/default/landmarks/discount_clothing.landmark.json';
import landmark19 from '../../packs/default/landmarks/discount_fashion.landmark.json';
import landmark20 from '../../packs/default/landmarks/discount_grocery.landmark.json';
import landmark21 from '../../packs/default/landmarks/discount_store.landmark.json';
import landmark22 from '../../packs/default/landmarks/donut_cafe.landmark.json';
import landmark23 from '../../packs/default/landmarks/electronics_store.landmark.json';
import landmark24 from '../../packs/default/landmarks/family_department_store.landmark.json';
import landmark25 from '../../packs/default/landmarks/fashion_department_store.landmark.json';
import landmark26 from '../../packs/default/landmarks/food_market.landmark.json';
import landmark27 from '../../packs/default/landmarks/fried_chicken.landmark.json';
import landmark28 from '../../packs/default/landmarks/furniture_store.landmark.json';
import landmark29 from '../../packs/default/landmarks/general_merchandise.landmark.json';
import landmark30 from '../../packs/default/landmarks/grocery.landmark.json';
import landmark31 from '../../packs/default/landmarks/grocery_market.landmark.json';
import landmark32 from '../../packs/default/landmarks/hardware_store.landmark.json';
import landmark33 from '../../packs/default/landmarks/home_improvement.landmark.json';
import landmark34 from '../../packs/default/landmarks/mall.landmark.json';
import landmark35 from '../../packs/default/landmarks/mart_store.landmark.json';
import landmark36 from '../../packs/default/landmarks/member_warehouse.landmark.json';
import landmark37 from '../../packs/default/landmarks/natural_grocery.landmark.json';
import landmark38 from '../../packs/default/landmarks/neighborhood_grocery.landmark.json';
import landmark39 from '../../packs/default/landmarks/outlet_mall.landmark.json';
import landmark40 from '../../packs/default/landmarks/pet_store.landmark.json';
import landmark41 from '../../packs/default/landmarks/pet_supply.landmark.json';
import landmark42 from '../../packs/default/landmarks/pharmacy.landmark.json';
import landmark43 from '../../packs/default/landmarks/pharmacy_store.landmark.json';
import landmark44 from '../../packs/default/landmarks/pizza_delivery.landmark.json';
import landmark45 from '../../packs/default/landmarks/pizza_place.landmark.json';
import landmark46 from '../../packs/default/landmarks/restaurant.landmark.json';
import landmark47 from '../../packs/default/landmarks/sandwich_shop.landmark.json';
import landmark48 from '../../packs/default/landmarks/shop.landmark.json';
import landmark49 from '../../packs/default/landmarks/sporting_goods.landmark.json';
import landmark50 from '../../packs/default/landmarks/street_lamp.landmark.json';
import landmark51 from '../../packs/default/landmarks/strip_mall.landmark.json';
import landmark52 from '../../packs/default/landmarks/supermarket.landmark.json';
import landmark53 from '../../packs/default/landmarks/taco_place.landmark.json';
import landmark54 from '../../packs/default/landmarks/traditional_department_store.landmark.json';
import landmark55 from '../../packs/default/landmarks/value_department_store.landmark.json';
import landmark56 from '../../packs/default/landmarks/variety_store.landmark.json';
import landmark57 from '../../packs/default/landmarks/warehouse_club.landmark.json';

export const rawLandmarkDocuments: Readonly<Record<string, unknown>> = {
  bench: landmark0,
  bike_rack: landmark1,
  'sign.bread_cafe': landmark2,
  'sign.burger_diner': landmark3,
  'sign.burger_place': landmark4,
  'sign.burger_restaurant': landmark5,
  'sign.burrito_grill': landmark6,
  'sign.cafe': landmark7,
  'charger.fast': landmark8,
  charger: landmark9,
  'sign.chicken_kitchen': landmark10,
  'sign.chicken_restaurant': landmark11,
  'sign.clothing_outlet': landmark12,
  'sign.coat_outlet': landmark13,
  'sign.coffee_shop': landmark14,
  'sign.community_market': landmark15,
  'sign.corner_pharmacy': landmark16,
  'sign.department_store': landmark17,
  'sign.discount_clothing': landmark18,
  'sign.discount_fashion': landmark19,
  'sign.discount_grocery': landmark20,
  'sign.discount_store': landmark21,
  'sign.donut_cafe': landmark22,
  'sign.electronics_store': landmark23,
  'sign.family_department_store': landmark24,
  'sign.fashion_department_store': landmark25,
  'sign.food_market': landmark26,
  'sign.fried_chicken': landmark27,
  'sign.furniture_store': landmark28,
  'sign.general_merchandise': landmark29,
  'sign.grocery': landmark30,
  'sign.grocery_market': landmark31,
  'sign.hardware_store': landmark32,
  'sign.home_improvement': landmark33,
  'sign.mall': landmark34,
  'sign.mart_store': landmark35,
  'sign.member_warehouse': landmark36,
  'sign.natural_grocery': landmark37,
  'sign.neighborhood_grocery': landmark38,
  'sign.outlet_mall': landmark39,
  'sign.pet_store': landmark40,
  'sign.pet_supply': landmark41,
  'sign.pharmacy': landmark42,
  'sign.pharmacy_store': landmark43,
  'sign.pizza_delivery': landmark44,
  'sign.pizza_place': landmark45,
  'sign.restaurant': landmark46,
  'sign.sandwich_shop': landmark47,
  'sign.shop': landmark48,
  'sign.sporting_goods': landmark49,
  street_lamp: landmark50,
  'sign.strip_mall': landmark51,
  'sign.supermarket': landmark52,
  'sign.taco_place': landmark53,
  'sign.traditional_department_store': landmark54,
  'sign.value_department_store': landmark55,
  'sign.variety_store': landmark56,
  'sign.warehouse_club': landmark57,
};
