// Removes node_modules and build outputs across the pnpm workspace so the repo
// can be reinstalled/rebuilt from a clean state. Useful when node_modules links
// get corrupted (e.g. junctions replaced by empty directories on a bad checkout).
//
// Usage:
//   node scripts/clean.mjs          # remove build outputs + node_modules (root + all packages/examples)
//   node scripts/clean.mjs --dist   # remove build outputs only, keep node_modules
import { readdir, rm, stat } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const distOnly = process.argv.includes('--dist');

// Gitignored build artifacts that are regenerated by `pnpm -r build`.
const OUTPUT_DIRS = ['dist', 'dist-types', 'coverage', '.tmp'];

async function exists(p) {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function subdirs(parent) {
  if (!(await exists(parent))) return [];
  const entries = await readdir(parent, { withFileTypes: true });
  return entries.filter((e) => e.isDirectory()).map((e) => join(parent, e.name));
}

async function remove(target) {
  if (!(await exists(target))) return;
  console.log(`  rm ${relative(root, target)}`);
  await rm(target, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
}

async function cleanDir(dir) {
  console.log(relative(root, dir) || '<root>');
  for (const out of OUTPUT_DIRS) await remove(join(dir, out));
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith('.tsbuildinfo')) await remove(join(dir, entry.name));
  }
  if (!distOnly) await remove(join(dir, 'node_modules'));
}

const targets = [
  root,
  ...(await subdirs(join(root, 'packages'))),
  ...(await subdirs(join(root, 'examples'))),
];

for (const dir of targets) await cleanDir(dir);

console.log(distOnly ? '\nBuild outputs removed.' : '\nClean complete. Run `pnpm install` next.');
